services:
  - type: worker
    name: fiyat-takip-botu
    env: python
    plan: free
    buildCommand: |
      pip install -r requirements.txt
      playwright install chromium
    startCommand: python main.py
